const fs = require('fs');
const p = 'public/divergencias.html';
let s = fs.readFileSync(p, 'utf8'); const crlf = s.includes('\r\n'); s = s.replace(/\r\n/g, '\n');
const tr = (de, para, r) => { if (s.split(de).length !== 2) throw new Error('ancora ' + r); s = s.replace(de, () => para); };
tr("  const D1 = tabela([...colsDec, {t: 'Motivo na Gestão', f: l => esc(l.motivo || '—')}, {t: 'No CEVEN hoje?', f: l => l.no_ceven ? 'sim' : '<b style=\"color:var(--aviso)\">não</b>'}], dc.nao_mostra,",
    "  const botoes = (l, novo) => `<div class=\"dec\"><button class=\"b-sim\" data-f=\"${esc(l.filial)}\" data-r=\"${esc(l.codigo)}\" data-m=\"1\" ${novo ? `data-n='${esc(JSON.stringify({nome: l.nome, supervisor: l.supervisor, canal: l.canal, gerente: l.gerente, grupo: l.grupo}))}'` : ''}>MOSTRAR</button><button class=\"b-nao\" data-f=\"${esc(l.filial)}\" data-r=\"${esc(l.codigo)}\" data-m=\"0\" ${novo ? `data-n='${esc(JSON.stringify({nome: l.nome, supervisor: l.supervisor, canal: l.canal, gerente: l.gerente, grupo: l.grupo}))}'` : ''}>NÃO MOSTRAR</button></div>`;\n" +
    "  const D1 = tabela([...colsDec, {t: 'Motivo na Gestão', f: l => esc(l.motivo || '—')}, {t: 'No CEVEN hoje?', f: l => l.no_ceven ? 'sim' : '<b style=\"color:var(--aviso)\">não</b>'}, {t: 'Decisão', f: l => botoes(l, false)}], dc.nao_mostra,", 'd1');
tr("{t: 'Hoje nas telas', f: l => '<span class=\"tag ok\">MOSTRA</span>'}], dc.fora_da_gestao,", "{t: 'Hoje nas telas', f: l => '<span class=\"tag ok\">MOSTRA</span>'}, {t: 'Decisão', f: l => botoes(l, true)}], dc.fora_da_gestao,", 'd2');
tr("  button { background:var(--acc);", "  .dec { display:flex; gap:6px; flex-wrap:wrap; } .dec button { padding:5px 10px; font-size:12px; white-space:nowrap; } .b-sim { background:var(--ok) !important; color:#04251a !important; } .b-nao { background:var(--ruim) !important; }\n  #senhaBox { display:flex; gap:8px; align-items:center; flex-wrap:wrap; margin:0 0 16px; } #senhaBox input { padding:7px 10px; border-radius:8px; border:1px solid var(--linha); background:var(--card); color:var(--tx); } #aviso { position:fixed; bottom:16px; left:50%; transform:translateX(-50%); background:var(--card); border:1px solid var(--linha); padding:10px 16px; border-radius:10px; display:none; z-index:9; }\n  button { background:var(--acc);", 'css');
tr('<div class="chips" id="chips"></div>', '<div id="senhaBox"><b>Senha da Diretoria</b> <input type="password" id="senha" placeholder="para gravar as decisões" autocomplete="off"> <span style="color:var(--mut)">Cada clique em MOSTRAR / NÃO MOSTRAR grava na Gestão de Equipe na hora.</span></div>\n<div class="chips" id="chips"></div>\n<div id="aviso"></div>', 'senha');
tr("$('btn').onclick = carrega;", "const avisa = (t) => { const a = $('aviso'); a.textContent = t; a.style.display = 'block'; setTimeout(() => { a.style.display = 'none'; }, 5000); };\ntry { $('senha').value = sessionStorage.getItem('ceven_senha_dir') || ''; } catch (e) {}\ndocument.addEventListener('click', async (ev) => {\n  const b = ev.target.closest('button[data-r]'); if (!b) return;\n  const senha = $('senha').value.trim(); if (!senha) { avisa('Digite a senha da Diretoria no topo da página.'); $('senha').focus(); return; }\n  b.disabled = true;\n  try {\n    const r = await fetch('/api/equipe-decidir', {method: 'POST', headers: {'Content-Type': 'application/json', 'X-Equipe-Senha': senha}, body: JSON.stringify({filial: b.dataset.f, rca: b.dataset.r, mostra: b.dataset.m === '1', novo: b.dataset.n ? JSON.parse(b.dataset.n) : undefined})});\n    const j = await r.json();\n    if (j.sucesso) { try { sessionStorage.setItem('ceven_senha_dir', senha); } catch (e) {} avisa('Gravado: ' + b.dataset.f + ' ' + b.dataset.r + ' → ' + (j.mostra ? 'MOSTRA' : 'NÃO MOSTRA')); await carrega(); }\n    else { avisa('Não gravou: ' + (j.erro || 'erro')); b.disabled = false; }\n  } catch (e) { avisa('Não consegui gravar agora.'); b.disabled = false; }\n});\n$('btn').onclick = carrega;", 'js');
fs.writeFileSync(p, crlf ? s.replace(/\n/g, '\r\n') : s); console.log('ok');
