const fs = require('fs');
function ed(rel, fn) { let s = fs.readFileSync(rel, 'utf8'); const crlf = s.includes('\r\n'); s = s.replace(/\r\n/g, '\n'); s = fn(s); fs.writeFileSync(rel, crlf ? s.replace(/\n/g, '\r\n') : s); console.log('ok', rel); }
const tr = (s, de, para, r) => { if (s.split(de).length !== 2) throw new Error('ancora ' + r + ' (' + (s.split(de).length - 1) + ')'); return s.replace(de, () => para); };

ed('functions/api/divergencias.js', (s) => {
  s = tr(s, "const decisao = { nao_mostra: [], fora_da_gestao: [] };", "const decisao = { nao_mostra: [], fora_da_gestao: [], sem_canal: [], canal_divergente: [] };", 'decl');
  s = tr(s, "        for (const x of decisao.nao_mostra) x.leitura = leitura(x);\n", "        // CANAL: o do CEVEN vale (area_atuacao). Vendedor que o CEVEN nao classifica (sem canal) e quem teve o canal trocado em relacao a Gestao aparecem aqui para o Vitório (22/09/2026: sem classificacao fica fora de Varejo e AS)\n        for (const k of Object.keys(cop.filiais)) {\n          const sig2 = k.split('_')[0].toUpperCase();\n          for (const v of cop.filiais[k] || []) {\n            if (!v || v.rca == null) continue;\n            if (v.canal_gestao !== undefined) decisao.canal_divergente.push(comNumeros({ filial: sig2, codigo: String(v.rca), nome: v.nome, supervisor: v.supervisor || '', canal_gestao: v.canal_gestao || '(vazio)', canal_ceven: v.canal, mostra: v.mostra !== false }, v.rca));\n            if (v.mostra !== false && !String(v.canal || '').trim()) { const it = comNumeros({ filial: sig2, codigo: String(v.rca), nome: v.nome, supervisor: v.supervisor || '', canal: '', motivo: 'CEVEN sem canal (sem classificação)' }, v.rca); it.leitura = leitura(it); decisao.sem_canal.push(it); }\n          }\n        }\n        decisao.canal_divergente.sort((a, b) => Number(b.mostra) - Number(a.mostra) || a.filial.localeCompare(b.filial));\n        for (const x of decisao.nao_mostra) x.leitura = leitura(x);\n", 'loop');
  return s;
});

ed('public/divergencias.html', (s) => {
  s = tr(s, "  const decisaoHtml = audHtml + confHtml + secao(", "  const D3 = tabela([...colsDec, {t: 'Decisão', f: l => botoes(l, false)}], fil(dc0.sem_canal || []), 'Nenhum vendedor visível sem canal no CEVEN.');\n  const D4 = tabela([{t: 'Filial', f: l => '<b>' + esc(l.filial) + '</b>'}, {t: 'Vendedor', f: l => esc(l.nome) + ' <span style=\"color:var(--mut)\">(' + esc(l.codigo) + ')</span>'}, {t: 'Supervisor', f: l => esc(l.supervisor || '—')}, {t: 'Canal na Gestão (antigo)', f: l => esc(l.canal_gestao)}, {t: 'Canal no CEVEN (vale)', f: l => '<b style=\"color:var(--ok)\">' + esc(l.canal_ceven) + '</b>'}, {t: 'Na tela', f: l => l.mostra ? 'MOSTRA' : '<span style=\"color:var(--mut)\">oculto</span>'}, {t: 'Faturado no mês', n: 1, f: l => brl(l.fat_mes)}], fil(dc0.canal_divergente || []), 'Nenhuma diferença de canal entre a Gestão e o CEVEN.');\n  const canalHtml = secao('C. Sem canal no CEVEN — decida (hoje contam como Varejo)', `${fil(dc0.sem_canal || []).length} vendedores visíveis que o CEVEN não classifica. Regra de 22/09/2026: sem classificação fica fora de Varejo e de AS. Se o vendedor deve disputar a liga, ajuste o canal no CEVEN; se não, marque NÃO MOSTRAR.`, D3) +\n    secao('D. Canal: o CEVEN passou a valer (Gestão x CEVEN)', `${fil(dc0.canal_divergente || []).length} vendedores tinham canal diferente na Gestão. Agora vale o canal do CEVEN (area_atuacao). Varejo = VJ, FARMA, PET VJ, ESP · AS = AS e PET AS · fora da liga: SUP, GER e sem classificação.`, D4);\n  const decisaoHtml = audHtml + confHtml + canalHtml + secao(", 'html');
  return s;
});
console.log('tudo ok');
