const fs = require('fs');
function ed(rel, fn) { let s = fs.readFileSync(rel, 'utf8'); const crlf = s.includes('\r\n'); s = s.replace(/\r\n/g, '\n'); s = fn(s); fs.writeFileSync(rel, crlf ? s.replace(/\n/g, '\r\n') : s); console.log('ok', rel); }
const tr = (s, de, para, r) => { if (s.split(de).length !== 2) throw new Error('ancora ' + r + ' ' + (s.split(de).length - 1)); return s.replace(de, () => para); };

// ATIVAR de vendedor que a Gestao ainda nao tinha: cria o registro ja mostrando
ed('functions/api/equipe-solicitacoes.js', (s) => tr(s,
  "            if (v) {\n              v.mostra = true;\n              v.motivo = '';\n            }\n",
  "            if (v) {\n              v.mostra = true;\n              v.motivo = '';\n            } else {\n              // vendedor da arvore viva do CEVEN ainda nao guardado na Gestao: grava o registro ja mostrando\n              let ex = {}; try { ex = JSON.parse(item.dados_extras || '{}'); } catch (e) {}\n              baseData.filiais[fil].unshift({ rca: /^[0-9]+$/.test(String(item.rca_id)) ? Number(item.rca_id) : item.rca_id, nome: item.rca_nome, canal: ex.canal || '', supervisor: ex.supervisor || '', gerente: ex.gerente || item.gerente_nome || '', grupo: ex.grupo || '', mostra: true, motivo: '' });\n            }\n", 'ativar'));

ed('public/divergencias.html', (s) => {
  s = tr(s, "<div id=\"senhaBox\">", "<div id=\"senhaBox\"><b>Seu nome</b> <input type=\"text\" id=\"nomeG\" placeholder=\"gerente da filial\" autocomplete=\"off\"> ", 'nome');
  s = tr(s, "<span style=\"color:var(--mut)\">Cada clique em MOSTRAR / NÃO MOSTRAR grava na Gestão de Equipe na hora.</span>", "<span style=\"color:var(--mut)\">Gerente: escolha a sua filial, digite seu nome e clique — vira um <b>pedido</b> com o motivo, que a Diretoria aprova. Diretoria: com a senha, o clique grava na hora e a fila de pedidos pode ser aprovada aqui mesmo.</span>", 'txt');
  s = tr(s, "  const botoes = (l, novo) => `<div class=\"dec\">", "  const botoes = (l, novo) => { const pd = PEND[l.filial + '|' + l.codigo]; return (pd ? `<div class=\"pend\">⏳ Pedido de ${pd.tipo_acao === 'OCULTAR' ? 'NÃO MOSTRAR' : 'MOSTRAR'} por ${esc(pd.gerente_nome)}: ${esc(pd.motivo || 'sem motivo')}</div>` : '') + `<div class=\"dec\">", 'bot1');
  s = s.split('<button class="b-sim" data-f="${esc(l.filial)}"').join('<button class="b-sim" data-nome="${esc(l.nome)}" data-f="${esc(l.filial)}"').split('<button class="b-nao" data-f="${esc(l.filial)}"').join('<button class="b-nao" data-nome="${esc(l.nome)}" data-f="${esc(l.filial)}"');
  s = tr(s, "NÃO MOSTRAR</button></div>`;\n", "NÃO MOSTRAR</button></div>`; };\n", 'bot2');
  s = tr(s, "  const dc0 = d.decisao || {nao_mostra: [], fora_da_gestao: []};\n", "  PEND = {}; let FILA = [];\n  try { const sj = await (await fetch('/api/equipe-solicitacoes?status=PENDENTE&t=' + Date.now())).json(); FILA = sj.solicitacoes || []; for (const x of FILA) PEND[x.filial + '|' + x.rca_id] = x; } catch (e) {}\n  const dc0 = d.decisao || {nao_mostra: [], fora_da_gestao: []};\n", 'fila');
  s = tr(s, "const dMeta = (L) =>", "const filaF = fAtual ? FILA.filter(x => x.filial === fAtual) : FILA;\n  const DQ = tabela([{t: 'Filial', f: l => '<b>' + esc(l.filial) + '</b>'}, {t: 'Vendedor', f: l => esc(l.rca_nome) + ' <span style=\"color:var(--mut)\">(' + esc(l.rca_id) + ')</span>'}, {t: 'Pedido', f: l => l.tipo_acao === 'OCULTAR' ? '<b style=\"color:var(--ruim)\">NÃO MOSTRAR</b>' : (l.tipo_acao === 'ATIVAR' ? '<b style=\"color:var(--ok)\">MOSTRAR</b>' : esc(l.tipo_acao))}, {t: 'Motivo', f: l => esc(l.motivo || '—')}, {t: 'Pedido por', f: l => esc(l.gerente_nome || '—') + ' <span style=\"color:var(--mut)\">' + esc(l.criado_em || '') + '</span>'}, {t: 'Diretoria', f: l => `<div class=\"dec\"><button class=\"b-sim\" data-sid=\"${l.id}\" data-a=\"APROVAR\">APROVAR</button><button class=\"b-nao\" data-sid=\"${l.id}\" data-a=\"REJEITAR\">REJEITAR</button></div>`}], filaF, 'Nenhum pedido aguardando aprovação.');\n  const dMeta = (L) =>", 'dq');
  s = tr(s, "  const decisaoHtml =\n", "  const decisaoHtml = secao('Pedidos dos gerentes aguardando a Diretoria', `${filaF.length} pedido(s). Aprovar grava na Gestão de Equipe na hora (precisa da senha da Diretoria no topo).`, DQ) +\n", 'dh');
  s = tr(s, "  .dec { display:flex;", "  .pend { font-size:11px; color:var(--aviso); margin-bottom:4px; max-width:260px; } .dec { display:flex;", 'css');
  s = tr(s, "const $ = (id) => document.getElementById(id);", "const $ = (id) => document.getElementById(id);\nlet PEND = {};", 'let');
  s = tr(s, "  const b = ev.target.closest('button[data-r]'); if (!b) return;\n  const senha = $('senha').value.trim(); if (!senha) { avisa('Digite a senha da Diretoria no topo da página.'); $('senha').focus(); return; }\n  b.disabled = true;\n",
"  const q = ev.target.closest('button[data-sid]');\n  if (q) {\n    const senhaQ = $('senha').value.trim(); if (!senhaQ) { avisa('Para aprovar ou rejeitar, digite a senha da Diretoria no topo.'); $('senha').focus(); return; }\n    q.disabled = true;\n    try {\n      const r = await fetch('/api/equipe-solicitacoes', {method: 'POST', headers: {'Content-Type': 'application/json', 'X-Equipe-Senha': senhaQ}, body: JSON.stringify({acao: q.dataset.a, solicitacao_id: Number(q.dataset.sid), usuario: 'Vitório Neto (Diretoria)'})});\n      const j = await r.json();\n      if (j.sucesso) { try { sessionStorage.setItem('ceven_senha_dir', senhaQ); } catch (e) {} avisa(j.mensagem || 'Feito.'); await carrega(); } else { avisa('Não gravou: ' + (j.erro || 'erro')); q.disabled = false; }\n    } catch (e) { avisa('Não consegui gravar agora.'); q.disabled = false; }\n    return;\n  }\n  const b = ev.target.closest('button[data-r]'); if (!b) return;\n  const senha = $('senha').value.trim();\n  if (!senha) { // GERENTE: vira um PEDIDO com motivo, que a Diretoria aprova\n    const nomeG = $('nomeG').value.trim(); if (!nomeG) { avisa('Digite seu nome no topo da página.'); $('nomeG').focus(); return; }\n    try { localStorage.setItem('ceven_div_nome', nomeG); } catch (e) {}\n    const quer = b.dataset.m === '1';\n    const motivo = (window.prompt('Motivo do pedido de ' + (quer ? 'MOSTRAR' : 'NÃO MOSTRAR') + ' — ' + (b.dataset.nome || b.dataset.r) + ' (obrigatório):') || '').trim();\n    if (!motivo) { avisa('Pedido não enviado: o motivo é obrigatório.'); return; }\n    b.disabled = true;\n    try {\n      const r = await fetch('/api/equipe-solicitacoes', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({filial: b.dataset.f, rca_id: b.dataset.r, rca_nome: b.dataset.nome, tipo_acao: quer ? 'ATIVAR' : 'OCULTAR', motivo, gerente_nome: nomeG, dados_extras: b.dataset.n ? JSON.parse(b.dataset.n) : {}})});\n      const j = await r.json();\n      if (j.sucesso) { avisa('Pedido enviado para a Diretoria aprovar.'); await carrega(); } else { avisa('Não enviou: ' + (j.erro || 'erro')); b.disabled = false; }\n    } catch (e) { avisa('Não consegui enviar agora.'); b.disabled = false; }\n    return;\n  }\n  b.disabled = true;\n", 'handler');
  s = tr(s, "try { $('senha').value = sessionStorage.getItem('ceven_senha_dir') || ''; } catch (e) {}", "try { $('senha').value = sessionStorage.getItem('ceven_senha_dir') || ''; $('nomeG').value = localStorage.getItem('ceven_div_nome') || ''; } catch (e) {}", 'init');
  return s;
});
